#! /bin/bash

#disable swapp
swapoff -a

#configure iptables to receive bridged network traffic
echo "net/bridge/bridge-nf-call-ip6tables = 1
net/bridge/bridge-nf-call-iptables = 1
net/bridge/bridge-nf-call-arptables = 1" >> /etc/ufw/sysctl.conf

#install ebtables ethtool
apt-get install ebtables ethtool

#install docker
apt-get update -y
apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

#add docker GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#add docker repository
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io

#sudo usermod -aG docker $USER
#newgrp docker #command which can reflect group changes in current session.


#add apt keys
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
#add repository
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF

#install kubelet kubeadm kubectl
apt-get update
apt-get install -y kubelet=1.15.3-00 kubeadm=1.15.3-00 kubectl=1.15.3-00 --allow-downgrades

#hold kubeadm kublet kubectl
sudo apt-mark hold kubectl kubeadm kubelet
